import { Metadata } from "next";
import TemplateTop from "../_components/templates/Top";

export const metadata: Metadata = {
  title: "Wippo",
  description: "Generated by create next app",
};


export default function Page() {
  return <TemplateTop />;
}
